language: python
python:
- "3.6"

# setup environment
env:
- DJANGO_VERSION=2.0.2

# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- coverage run --source=. --omit '*__init__*,*wsgi*,*manage*,*test*,*environment.py*,*settings/*,*sdp/apps*,*sdp/urls*,*SdpREST/fixtures*,*SdpREST/urls*' manage.py test sdp --noinput --settings=SdpREST.settings.dev

# run coveralls after successful tests
after_success:
- codecov


