# Generated by Django 2.0.2 on 2018-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-id'],
            },
        ),
    ]
