# Generated by Django 2.0.2 on 2018-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='local',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
